version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    entrypoint: ["sh", "FLASK_APP=/usr/src/jwt-app/app.py flask run --host=0.0.0.0"] # new
    volumes:
      - "./server:/usr/src/flask-jwt"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:19761976@localhost:5432/flask_db
      - SECRET_KEY=DXBSLK0UoJedIohhn7VYP0fqJNI1DQCKqWWh2zLjB2s
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=19761976

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./services/frontend:/usr/src/chat-app"
      - "/usr/src/chat-app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_SERVICE_URL=http://localhost:5004
      - REACT_APP_WEBSOCKET_SERVICE_URL=http://localhost:5001
    depends_on:
      - server